"$schema" = 'https://starship.rs/config-schema.json'

format = '$directory$fill$time$line_break $all$cmd_duration$line_break$character'

[username]
disabled = true

[hostname]
style="white"

[fill]
symbol = '  '

[shell]
disabled = false
style = "bold"
bash_indicator = "[bsh](#d274f6)"
zsh_indicator = "[zsh](#fff1b9)"
fish_indicator = "[fsh](#2998fd)"
powershell_indicator = "[psh](#f7aa97)"
cmd_indicator = "[cmd](#a3daff)"

[character]
success_symbol = "[❯❯](bold #00ff00)"
error_symbol = "[✘](bold #ff4444)"

[directory]
truncation_length = 1000
style = "bold #00FFFF"
truncate_to_repo = false

[time]
disabled = false
format = "[$time]($style) "
style = "bold #ffff00"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bold #ff88ff"

[cmd_duration]
format = "[$duration]($style) "
show_milliseconds = true
style = "bold #ff9900"
min_time = 1_000

[c]
disabled = true

[golang]
disabled = true

[rust]
disabled = true
